### ISSUE TITLE
issue/Task4.md

### ISSUE THREAD

**Issue by EthanNing** [csci3250-2019/project-team-g#22]
Write C code.

**Comment by YuChaoGithub** [comment]
`code.c` can't compile. The `int` before the `main(...)` and `void` before `lastDigit(...)` is missing.

**Comment by NgChiu** [comment]
Remember to include the code into the `README.md`.

**Comment by destiny0313** [comment]
Sorry for being late to join the group.
I have written some codes in the code.c file.

**Comment by jauyong9** [comment]
#34 I have added the Travis CI build status. Please review and merge the pull request.

**Comment by jauyong9** [comment]
Task completed. I will close this issue.
