### ISSUE TITLE
issue/Task5.md

### ISSUE THREAD

**Issue by destiny0313** [csci3250-2019/project-team-g#35]
Task 5: Promote your repo

Go to the public repo of csci3250-2019.github.io in the CSCI3250 organization
Edit the file to add a link of your team (https://csci3250-2019.github.io/(repo name)), and request for review from @chuckjee

**Comment by justinsochi** [comment]
who wanna do this issue? i have already completed issue 1.

**Comment by jojoyui** [comment]
I have edited the file and asking chukjee for the review!

**Comment by chloeisclever** [comment]
sorry for being late, I will try to view the edited

**Comment by jojoyui** [comment]
task completed, I will close this issue.
