### ISSUE TITLE
issue/Task1.md

### ISSUE THREAD

**Issue by justinsochi** [csci3250-2019/project-team-g#4]
I will work on issue 1,
please tell me below about how can we improve and make it better.

**Comment by YuChaoGithub** [comment]
I actually already merged your pull request already 😅. By the way, you have to assign your self to this issue on the right panel.

**Comment by justinsochi** [comment]
Oh, Thank you for your kindly reminder!

**Comment by YuChaoGithub** [comment]
This task is done, I'll close it.
